esphome:
  name: s3rai00
  friendly_name: S3RAI00

# Import the comprehensive M5Stack AtomS3R-AI configuration
packages:
  m5stack-s3rai: 
    url: https://github.com/dougmorato/wake-word-voice-assistants
    ref: main
    files: [m5stack-atoms3r-ai/m5stack-atoms3r-ai.yaml]
    refresh: always

esp32:
  board: m5stack-atoms3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR_ENCRYPTION_KEY_HERE"

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD_HERE"

# WiFi configuration - replace with your network credentials. This config uses ESPHome secrets variables.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3RAI00 Fallback Hotspot"
    password: "d0UgK7prnTbI"

captive_portal:

# Optional: Override any settings from the package
# Uncomment and modify as needed:

# substitutions:
#   # Override illustration URLs with your own
#   idle_illustration_file: "https://your-server.com/your-idle-image.png"
#   
#   # Override colors
#   idle_illustration_background_color: "001122"

# wifi:
#   # Add additional wifi networks
#   networks:
#     - ssid: "Guest-Network"  
#       password: "guest-password"